# Generated by Django 3.2.5 on 2021-07-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_createdat_voiceprint_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceprint',
            name='date',
        ),
    ]
