# Generated by Django 3.2.5 on 2021-07-09 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_voiceprint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprint',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
