# Generated by Django 3.2.5 on 2021-07-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_voiceprint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprint',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
